"""world 0.1 独立验收的冻结矩阵（票 #27）：由规格 #17「测试决定」主缝清单导出，缺检查、未运行都不算通过。

分组即票面清单十二项，每条检查只属于一组；COVERAGE 是 13 个动作 × 通过与五类拒绝的交叉索引，
引用的检查都在 MATRIX 里；不适用的格子在 NOT_APPLICABLE 写明理由。本模块不导入被测实现。
"""

SOURCES = {
    'protocol': 'tkos.world/0.1',
    'spec': 'GitHub issue #17（测试决定：主缝）',
    'ticket': 'GitHub issue #27',
    'contract': 'docs/contracts/tkos-world-0.1.md',
    'base_commit': 'ef31b02',
}

TITLES = {
    'WORLD-01': '迁移升级与幂等',
    'WORLD-02': '控制面安装四步',
    'WORLD-03': '13 个动作的通过与拒绝',
    'WORLD-04': '门按目标类型判权',
    'WORLD-05': '退回与撤回',
    'WORLD-06': '确认写回与生效指针',
    'WORLD-07': '快照唯一性',
    'WORLD-08': '引用钉定',
    'WORLD-09': '四个读投影',
    'WORLD-10': '上下文包落表',
    'WORLD-11': '读权限',
    'WORLD-12': 'MCP 端到端',
}

ACTIONS = (
    'world_create_object', 'world_revise_object', 'world_relate', 'world_refresh_state', 'world_record_event',
    'world_assign', 'world_commit_period_goal', 'world_commit_mission', 'world_confirm_long_term_goal',
    'world_confirm_period_goal', 'world_confirm_mission', 'world_confirm_mission_core_battle', 'world_mark_core_battle',
)
GATE_ACTIONS = ACTIONS[6:]
KINDS = ('passes', 'wrong_role', 'wrong_state', 'missing_declaration', 'wrong_expected_version', 'wrong_reference')


def _per_gate(template):
    return [template.format(kind=kind) for kind in GATE_ACTIONS]


MATRIX = {
    'WORLD-01': [
        'the_database_was_created_fresh_from_the_accepted_baseline',
        'the_upgrade_applied_exactly_the_world_migrations_of_the_accepted_source',
        'repeating_either_migration_applies_nothing',
        'the_world_migration_is_the_newest_applied_migration',
    ],
    'WORLD-02': [
        'install_profile_records_the_world_profile_pinned_to_the_contract_and_registry_bytes',
        'a_profile_install_with_other_contract_bytes_is_refused_and_nothing_is_left_behind',
        'a_profile_install_with_other_registry_bytes_is_refused_and_nothing_is_left_behind',
        'install_policy_makes_world_the_default_protocol_of_the_scope',
        'set_registry_lists_the_implemented_world_actions_and_types',
        'each_domain_gets_its_activation_policy_from_the_control_plane_with_one_control_event_each',
        'the_installed_policies_carry_the_gate_roles_of_the_registry',
        'an_activation_policy_with_an_unknown_role_is_refused_and_nothing_is_left_behind',
        'an_activation_policy_with_an_empty_role_list_is_refused_and_nothing_is_left_behind',
        'an_activation_policy_with_a_domain_of_another_scope_is_refused_and_nothing_is_left_behind',
        'an_activation_policy_with_content_the_database_refuses_after_the_epoch_moved_is_refused_and_nothing_is_left_behind',
        'the_binding_pins_the_world_profile_through_the_world_gate',
        'the_world_gate_refuses_a_world_binding_whose_profile_does_not_pin_the_exact_contract',
        'a_scope_without_world_answers_protocol_not_supported_and_writes_nothing',
    ],
    'WORLD-03': [
        # world_create_object
        'the_ceo_creates_the_company_over_http',
        'exactly_one_object_created_event_points_back_to_its_receipt',
        'exactly_one_receipt_is_written_for_the_creation',
        'replaying_the_same_command_returns_the_original_receipt',
        'reusing_a_key_for_a_different_command_is_refused',
        'an_ic_cannot_create_the_company',
        'an_agent_cannot_create_the_company',
        'a_payload_field_outside_the_contract_is_refused',
        'an_empty_block_cannot_pose_as_content',
        'a_scope_has_exactly_one_company',
        'a_wrong_expected_version_is_refused',
        'an_action_of_another_protocol_cannot_touch_a_world_object',
        'authorization_is_refused_before_any_protocol_error',
        'the_ceo_and_the_unit_dri_create_the_whole_spine_over_http',
        'each_creation_writes_one_pinned_event_and_binds_through_the_repinned_world_gate',
        'a_person_may_write_without_a_declaration_and_one_given_is_pinned_into_the_receipt',
        'a_reference_to_an_unknown_object_is_refused',
        'a_reference_to_an_unknown_version_is_refused',
        'a_reference_to_a_block_its_type_does_not_have_is_refused',
        'a_field_outside_the_contract_is_refused',
        'a_cross_chain_relation_is_not_written_by_creation',
        'a_strategy_outside_the_company_domain_is_refused',
        'a_unit_in_the_company_domain_is_refused',
        'a_mission_in_another_unit_than_its_period_goal_is_refused',
        'a_company_goal_hanging_on_a_unit_is_refused',
        'a_company_goal_with_a_goal_ref_is_refused',
        'a_unit_goal_decomposing_a_unit_goal_is_refused',
        'a_period_goal_advancing_a_company_goal_is_refused',
        'a_task_under_a_task_is_refused',
        'a_domain_has_exactly_one_responsibility_unit',
        'a_state_snapshot_is_not_written_by_creation',
        'a_dri_cannot_create_in_a_domain_where_they_hold_no_role',
        'only_the_ceo_creates_a_responsibility_unit',
        'an_ic_cannot_create_a_strategy',
        'a_dri_cannot_create_under_another_units_goal',
        'an_agent_write_without_a_declaration_is_refused',
        'an_agent_write_missing_its_scene_is_refused',
        'an_agent_write_missing_its_trigger_is_refused',
        'an_agent_write_missing_its_human_acceptance_is_refused',
        'a_declared_agent_still_needs_to_be_responsible_up_the_spine',
        'a_declaration_whose_scene_is_not_a_mission_or_task_is_refused',
        'a_declaration_whose_acceptor_is_an_agent_is_refused',
        'a_declaration_whose_acceptor_holds_no_role_in_the_scope_is_refused',
        'a_declaration_whose_acceptor_is_unknown_is_refused',
        'a_revoked_ceo_cannot_replay_the_creation_into_a_success',
        # world_revise_object
        'a_revision_changes_only_what_it_names_and_the_rest_carries_over',
        'a_revision_writes_one_object_revised_event_pinned_to_the_new_version',
        'a_replayed_revision_returns_its_receipt_and_a_reused_key_for_another_patch_is_refused',
        'a_draft_gated_goal_is_revised_without_moving_its_formal_pointer_and_a_task_by_its_unit_dri',
        'someone_not_responsible_up_the_spine_cannot_revise',
        'a_unit_member_who_is_not_responsible_cannot_revise_a_task',
        'an_agent_cannot_revise_a_gated_type',
        'an_agent_revision_without_a_declaration_is_refused',
        'an_agent_revision_must_ask_for_human_acceptance',
        'a_declared_agent_still_needs_to_be_responsible_to_revise',
        'a_revision_with_a_wrong_expected_version_is_refused',
        'a_revision_cannot_move_an_object_under_another_parent',
        'a_revision_cannot_drop_a_creation_reference',
        'a_revision_cannot_write_a_field_only_the_service_writes',
        'a_revision_citing_an_unknown_version_is_refused',
        'a_revision_whose_target_is_not_the_latest_revision_is_refused',
        # world_relate
        'relations_read_back_pinned_on_the_object_that_holds_them_and_the_other_end_is_untouched',
        'each_relate_writes_exactly_one_relate_event_naming_both_ends',
        'the_other_end_lists_the_relations_that_point_at_it',
        'a_relation_list_is_replaced_as_a_whole_so_it_can_be_emptied_and_a_replay_changes_nothing',
        'someone_not_responsible_cannot_relate',
        'an_object_cannot_depend_on_itself',
        'a_contribution_goes_to_another_units_goal',
        'a_contribution_does_not_go_to_a_company_level_goal',
        'a_relation_points_to_a_type_the_registry_allows',
        'a_relation_field_the_type_does_not_have_is_refused',
        'an_agent_relation_without_a_declaration_is_refused',
        'a_relation_with_a_wrong_expected_version_is_refused',
        'a_relation_to_an_unknown_version_is_refused',
        'a_relation_whose_target_is_not_the_latest_revision_is_refused',
        # world_refresh_state
        'a_unit_dri_and_a_unit_agent_write_snapshots_stored_in_the_subjects_domain_with_utc_text',
        'a_snapshot_write_records_one_state_refreshed_event_naming_the_snapshot_then_its_subject',
        'a_person_not_responsible_up_the_spine_cannot_write_a_snapshot',
        'an_agent_without_the_agent_role_in_the_unit_cannot_write_a_snapshot',
        'a_snapshot_cannot_be_the_subject_of_a_snapshot',
        'a_snapshot_with_a_wrong_expected_version_is_refused',
        'a_snapshot_of_an_unknown_subject_version_is_refused',
        # world_record_event
        'an_external_event_that_happened_earlier_is_recorded_at_its_own_occurred_at',
        'events_are_recorded_by_scope_permission_regardless_of_any_domain_policy',
        'a_unit_agent_records_an_event_with_its_declaration',
        'a_correction_references_the_original_which_stays_unchanged',
        'an_event_without_subjects_is_refused',
        'a_replayed_event_returns_its_receipt_and_a_reused_key_for_another_event_is_refused',
        'an_agent_event_or_snapshot_without_a_declaration_is_refused',
        'an_event_or_snapshot_dated_in_the_future_is_refused',
        'a_correction_can_only_correct_an_external_event',
        'an_event_with_a_wrong_expected_version_is_refused',
        'an_event_about_an_unknown_version_is_refused',
        # world_assign，以及由动作推导的 Task 与 Activity 生命周期
        'the_ceo_assigns_the_unit_dri_as_a_record_without_a_new_version',
        'the_dri_assigns_the_mission_owner_as_a_new_version_without_moving_its_lifecycle',
        'the_owner_assigns_the_task_and_snapshots_written_before_assignment_do_not_count',
        'an_activity_moves_assigned_in_progress_delivered_with_each_step_naming_its_event',
        'an_acceptance_by_someone_other_than_the_task_responsible_does_not_close_the_activity',
        'the_task_responsible_closes_the_activity_by_acceptance',
        'the_owner_creates_under_the_mission_the_task_responsible_revises_the_task_and_the_activity_agent_revises_it',
        'the_owner_writes_a_snapshot_and_relates_the_mission_and_the_task_responsible_moves_the_task_to_delivered',
        'a_dri_cannot_skip_the_owner_to_assign_a_task',
        'the_ceo_cannot_skip_levels_to_assign_an_activity',
        'a_task_responsible_does_not_assign_activities',
        'a_mission_owner_must_hold_the_owner_role',
        'a_task_responsible_must_be_a_person',
        'an_unknown_assignee_is_refused',
        'a_goal_is_not_assigned',
        'an_agent_holding_the_dri_role_cannot_assign',
        'an_assignment_whose_target_is_not_the_latest_revision_is_refused',
        'a_former_task_responsible_cannot_replay_a_revision_after_the_task_is_reassigned',
        'a_replayed_assignment_returns_its_receipt_a_reused_key_is_refused_and_a_stale_version_conflicts',
        'an_owner_who_lost_the_owner_role_can_neither_create_nor_replay_a_creation',
        'an_acceptance_by_an_owner_without_the_owner_role_does_not_close_the_task',
        # 七个门动作：各自的错状态、错期望版本、错引用，以及门的重放
        'the_first_snapshot_puts_it_in_progress',
        'a_replayed_gate_returns_its_receipt_and_a_reused_key_for_another_candidate_is_refused',
        'a_mission_is_marked_a_core_battle_once',
        *_per_gate('{kind}_in_a_state_the_gate_does_not_allow_is_refused'),
        *_per_gate('{kind}_with_a_wrong_expected_version_is_refused'),
        *_per_gate('{kind}_citing_an_unknown_version_is_refused'),
        *_per_gate('{kind}_whose_target_is_not_the_latest_revision_is_refused'),
    ],
    'WORLD-04': [
        *_per_gate('{kind}_by_a_role_the_policy_does_not_list_is_refused'),
        'an_owner_role_alone_does_not_commit_someone_elses_mission',
        'an_agent_holding_the_dri_role_cannot_sign_a_gate',
        'a_gate_on_a_type_it_does_not_name_is_refused',
    ],
    'WORLD-05': [
        'withdrawing_a_confirmation_that_did_not_make_the_content_formal_leaves_the_formal_pointer',
        'the_dri_returns_the_delivery_for_adjustment',
        'the_owner_commits_the_delivery_again_from_adjustment',
        'a_returned_long_term_goal_stays_a_draft_with_the_return_on_record',
        'withdrawing_the_confirmation_takes_the_formal_content_back_with_the_lifecycle',
        'a_mistaken_commitment_is_withdrawn_by_the_same_role_and_the_original_event_stays',
        'a_period_goal_is_returned_revised_as_a_draft_committed_again_and_confirmed',
        'a_returned_candidate_is_discarded_and_nothing_is_left_to_confirm',
        'a_return_to_draft_takes_the_formal_content_back_and_cannot_be_withdrawn',
        'a_withdrawal_is_recorded_by_the_same_gate_action_as_the_event_it_withdraws',
        'only_the_gate_event_that_produced_the_current_stage_is_withdrawn',
    ],
    'WORLD-06': [
        'the_owner_commits_the_initiation_and_the_content_is_not_formal_yet',
        'the_dri_accepts_the_initiation_and_the_confirmed_revision_becomes_the_formal_content',
        'the_ceo_marks_the_established_mission_a_core_battle_which_now_awaits_the_ceo',
        'the_ceo_confirms_the_core_battle_initiation',
        'an_established_mission_is_not_revised_directly',
        'a_rerun_commitment_carries_its_candidate_and_nothing_formal_changes_until_the_last_confirmation',
        'the_ceo_acceptance_writes_the_candidate_back_as_the_new_formal_version_without_moving_the_lifecycle',
        'the_owner_commits_the_delivery',
        'the_dri_closes_the_delivery_and_every_gate_event_is_listed_with_its_action_phase_and_outcome',
        'the_ceo_confirms_the_revised_long_term_goal',
        'a_confirmed_long_term_goal_is_changed_by_a_ceo_confirmation_that_carries_the_new_content',
        'a_confirmed_period_goal_is_not_revised_directly',
        'a_second_candidate_waits_for_the_first_to_be_confirmed_or_returned',
        'the_ceo_confirmation_writes_the_period_goal_candidate_back',
        'a_mission_that_is_not_a_core_battle_writes_its_candidate_back_when_the_dri_accepts',
        'one_ceo_acceptance_establishes_a_mission_marked_during_a_rerun_and_writes_its_candidate_back',
        'a_draft_carries_no_candidate_because_it_is_revised_directly',
        'a_rerun_commitment_must_carry_its_candidate',
    ],
    'WORLD-07': [
        'a_second_snapshot_of_the_same_subject_at_the_same_instant_is_refused',
        'a_replayed_snapshot_write_returns_its_receipt_and_a_reused_key_for_another_snapshot_is_refused',
    ],
    'WORLD-08': [
        'relation_refs_read_back_pinned_to_the_referenced_revision',
        'block_refs_read_back_pinned_and_an_empty_block_can_be_cited',
        'references_stay_pinned_after_the_referenced_objects_get_new_versions',
        'a_creation_reference_can_follow_the_same_object_to_a_newer_version',
    ],
    'WORLD-09': [
        # 取对象
        'the_object_view_renders_blocks_citations_and_the_empty_block_sentence',
        'the_company_is_formal_on_creation_and_read_as_world_0_1',
        'attributes_read_back_as_written_and_server_owned_ones_start_empty',
        'gated_types_start_as_draft_and_the_rest_are_formal_on_creation',
        'the_old_version_is_still_read_by_its_number_and_the_new_one_supersedes_it',
        'a_version_that_does_not_exist_is_not_found',
        'types_without_a_lifecycle_read_none_and_gated_objects_start_as_drafts_produced_by_creation',
        'children_are_all_and_only_the_objects_whose_parent_ref_points_at_the_object',
        # 取状态与取事件
        'get_state_returns_the_latest_snapshot_not_later_than_the_given_time',
        'get_object_carries_the_latest_snapshot_and_every_snapshot_read_is_marked_unconfirmed',
        'get_events_lists_every_event_about_the_object_in_occurred_at_order_and_marks_corrections',
        'get_events_starts_at_the_given_time',
        # 取上下文
        'the_context_walks_the_spine_from_the_activity_up_to_the_company',
        'every_block_is_cited_to_the_version_read_and_an_empty_block_reads_the_standard_sentence',
        'snapshots_and_recent_events_come_only_from_the_execution_chain_and_each_event_appears_once',
        'cross_chain_relations_are_listed_as_references_and_not_followed',
        'a_responsible_who_no_longer_holds_the_role_is_not_listed_as_responsible',
        'coverage_answers_the_six_questions_with_evidence_taken_from_the_pack',
        'a_tight_budget_trims_old_events_first_then_blocks_from_the_farthest_levels_and_records_why',
        'the_current_object_keeps_its_blocks_and_snapshot_under_any_budget',
        'coverage_follows_what_survived_the_trim',
        'the_per_object_event_cap_keeps_the_newest_event_per_level_and_records_the_rest',
        'recent_events_start_at_the_requested_window',
        'starting_from_a_snapshot_takes_its_subject_as_the_current_object_and_that_snapshot_as_its_state',
        'starting_from_the_company_reads_one_level_with_its_ceo_as_responsible',
        'a_bare_unassigned_activity_reports_what_and_who_as_gaps_with_reasons',
    ],
    'WORLD-10': [
        'each_call_writes_exactly_one_context_pack_row_holding_what_was_returned',
        'two_calls_on_the_same_world_state_cite_the_same_references',
        'identities_outside_the_scope_bad_questions_and_unknown_objects_are_refused_and_write_nothing',
    ],
    'WORLD-11': [
        'an_identity_assigned_only_in_another_domain_reads_the_company_by_the_world_rule',
        'the_world_receipt_is_read_by_the_world_rule',
        'an_identity_from_another_scope_cannot_read_the_company',
        'an_identity_from_another_scope_cannot_list_children',
        'an_identity_from_another_scope_reads_neither_events_nor_state',
        'an_identity_without_a_current_assignment_in_the_scope_can_neither_record_replay_nor_read',
    ],
    'WORLD-12': [
        'the_mcp_server_lists_the_four_reads_and_three_writes_and_no_gate_assignment_or_relation',
        'the_four_reads_reach_the_real_api_with_the_agent_credential',
        'the_three_writes_commit_through_prepare_and_commit_as_the_agent',
        'a_write_missing_its_declaration_or_any_of_its_three_items_is_refused_by_http_and_returned_verbatim',
        'every_mcp_call_is_in_the_run_log_with_its_references_and_no_credential',
    ],
}

_GATE_PASSES = {
    'world_commit_period_goal': ['a_mistaken_commitment_is_withdrawn_by_the_same_role_and_the_original_event_stays',
                                 'a_period_goal_is_returned_revised_as_a_draft_committed_again_and_confirmed'],
    'world_commit_mission': ['the_owner_commits_the_initiation_and_the_content_is_not_formal_yet',
                             'the_owner_commits_the_delivery'],
    'world_confirm_long_term_goal': ['the_ceo_confirms_the_revised_long_term_goal'],
    'world_confirm_period_goal': ['a_period_goal_is_returned_revised_as_a_draft_committed_again_and_confirmed',
                                  'the_ceo_confirmation_writes_the_period_goal_candidate_back'],
    'world_confirm_mission': ['the_dri_accepts_the_initiation_and_the_confirmed_revision_becomes_the_formal_content',
                              'the_dri_closes_the_delivery_and_every_gate_event_is_listed_with_its_action_phase_and_outcome'],
    'world_confirm_mission_core_battle': ['the_ceo_confirms_the_core_battle_initiation'],
    'world_mark_core_battle': ['the_ceo_marks_the_established_mission_a_core_battle_which_now_awaits_the_ceo'],
}
_GATE_EXTRA_ROLES = {
    'world_commit_mission': ['an_owner_role_alone_does_not_commit_someone_elses_mission'],
    'world_confirm_mission': ['an_agent_holding_the_dri_role_cannot_sign_a_gate'],
}
_GATE_EXTRA_STATES = {
    'world_commit_period_goal': ['a_second_candidate_waits_for_the_first_to_be_confirmed_or_returned'],
    'world_mark_core_battle': ['a_mission_is_marked_a_core_battle_once'],
}

COVERAGE = {
    'world_create_object': {
        'passes': ['the_ceo_creates_the_company_over_http', 'the_ceo_and_the_unit_dri_create_the_whole_spine_over_http'],
        'wrong_role': ['an_ic_cannot_create_the_company', 'an_agent_cannot_create_the_company',
                       'a_dri_cannot_create_in_a_domain_where_they_hold_no_role', 'only_the_ceo_creates_a_responsibility_unit',
                       'an_ic_cannot_create_a_strategy', 'a_dri_cannot_create_under_another_units_goal'],
        'wrong_state': ['a_scope_has_exactly_one_company', 'a_domain_has_exactly_one_responsibility_unit'],
        'missing_declaration': ['an_agent_write_without_a_declaration_is_refused',
                                'an_agent_write_missing_its_scene_is_refused', 'an_agent_write_missing_its_trigger_is_refused',
                                'an_agent_write_missing_its_human_acceptance_is_refused'],
        'wrong_expected_version': ['a_wrong_expected_version_is_refused'],
        'wrong_reference': ['a_reference_to_an_unknown_object_is_refused', 'a_reference_to_an_unknown_version_is_refused',
                            'a_reference_to_a_block_its_type_does_not_have_is_refused'],
    },
    'world_revise_object': {
        'passes': ['a_revision_changes_only_what_it_names_and_the_rest_carries_over',
                   'the_owner_creates_under_the_mission_the_task_responsible_revises_the_task_and_the_activity_agent_revises_it'],
        'wrong_role': ['someone_not_responsible_up_the_spine_cannot_revise',
                       'a_unit_member_who_is_not_responsible_cannot_revise_a_task', 'an_agent_cannot_revise_a_gated_type'],
        'wrong_state': ['an_established_mission_is_not_revised_directly', 'a_confirmed_period_goal_is_not_revised_directly'],
        'missing_declaration': ['an_agent_revision_without_a_declaration_is_refused',
                                'an_agent_revision_must_ask_for_human_acceptance'],
        'wrong_expected_version': ['a_revision_with_a_wrong_expected_version_is_refused'],
        'wrong_reference': ['a_revision_citing_an_unknown_version_is_refused',
                            'a_revision_whose_target_is_not_the_latest_revision_is_refused'],
    },
    'world_relate': {
        'passes': ['relations_read_back_pinned_on_the_object_that_holds_them_and_the_other_end_is_untouched',
                   'a_relation_list_is_replaced_as_a_whole_so_it_can_be_emptied_and_a_replay_changes_nothing'],
        'wrong_role': ['someone_not_responsible_cannot_relate'],
        'missing_declaration': ['an_agent_relation_without_a_declaration_is_refused'],
        'wrong_expected_version': ['a_relation_with_a_wrong_expected_version_is_refused'],
        'wrong_reference': ['a_relation_to_an_unknown_version_is_refused', 'a_relation_points_to_a_type_the_registry_allows',
                            'a_relation_whose_target_is_not_the_latest_revision_is_refused'],
    },
    'world_refresh_state': {
        'passes': ['a_unit_dri_and_a_unit_agent_write_snapshots_stored_in_the_subjects_domain_with_utc_text'],
        'wrong_role': ['a_person_not_responsible_up_the_spine_cannot_write_a_snapshot',
                       'an_agent_without_the_agent_role_in_the_unit_cannot_write_a_snapshot'],
        'wrong_state': ['a_second_snapshot_of_the_same_subject_at_the_same_instant_is_refused'],
        'missing_declaration': ['an_agent_event_or_snapshot_without_a_declaration_is_refused'],
        'wrong_expected_version': ['a_snapshot_with_a_wrong_expected_version_is_refused'],
        'wrong_reference': ['a_snapshot_of_an_unknown_subject_version_is_refused',
                            'a_snapshot_cannot_be_the_subject_of_a_snapshot'],
    },
    'world_record_event': {
        'passes': ['an_external_event_that_happened_earlier_is_recorded_at_its_own_occurred_at',
                   'events_are_recorded_by_scope_permission_regardless_of_any_domain_policy',
                   'a_unit_agent_records_an_event_with_its_declaration'],
        'wrong_role': ['an_identity_without_a_current_assignment_in_the_scope_can_neither_record_replay_nor_read'],
        'missing_declaration': ['an_agent_event_or_snapshot_without_a_declaration_is_refused'],
        'wrong_expected_version': ['an_event_with_a_wrong_expected_version_is_refused'],
        'wrong_reference': ['an_event_about_an_unknown_version_is_refused', 'a_correction_can_only_correct_an_external_event'],
    },
    'world_assign': {
        'passes': ['the_ceo_assigns_the_unit_dri_as_a_record_without_a_new_version',
                   'the_dri_assigns_the_mission_owner_as_a_new_version_without_moving_its_lifecycle',
                   'the_owner_assigns_the_task_and_snapshots_written_before_assignment_do_not_count'],
        'wrong_role': ['a_dri_cannot_skip_the_owner_to_assign_a_task', 'the_ceo_cannot_skip_levels_to_assign_an_activity',
                       'a_task_responsible_does_not_assign_activities', 'a_mission_owner_must_hold_the_owner_role',
                       'a_task_responsible_must_be_a_person', 'an_agent_holding_the_dri_role_cannot_assign'],
        'wrong_expected_version': ['a_replayed_assignment_returns_its_receipt_a_reused_key_is_refused_and_a_stale_version_conflicts'],
        'wrong_reference': ['an_assignment_whose_target_is_not_the_latest_revision_is_refused'],
    },
    **{kind: {
        'passes': _GATE_PASSES[kind],
        'wrong_role': [f'{kind}_by_a_role_the_policy_does_not_list_is_refused', *_GATE_EXTRA_ROLES.get(kind, [])],
        'wrong_state': [f'{kind}_in_a_state_the_gate_does_not_allow_is_refused', *_GATE_EXTRA_STATES.get(kind, [])],
        'wrong_expected_version': [f'{kind}_with_a_wrong_expected_version_is_refused'],
        'wrong_reference': [f'{kind}_citing_an_unknown_version_is_refused',
                            f'{kind}_whose_target_is_not_the_latest_revision_is_refused'],
    } for kind in GATE_ACTIONS},
}

_GATES_ARE_SIGNED_BY_PEOPLE = ('门只由人签，不带写入声明（契约第 9 节）；七个门动作共用同一处人身份检查，Agent 签门被拒见 '
                               'an_agent_holding_the_dri_role_cannot_sign_a_gate。')
NOT_APPLICABLE = {
    'world_relate': {'wrong_state': '建关系不看生命周期：跨链关系不属于正式内容块，有门对象成立后建关系也不重走承诺与确认（契约第 9 节）。'},
    'world_record_event': {'wrong_state': '外部事件按 scope 判权，不看任何对象的生命周期（契约第 8 节）。'},
    'world_assign': {'wrong_state': '指派不看生命周期，可以改派（契约第 9 节）。',
                     'missing_declaration': '指派者都是人，指派不带写入声明（契约第 9 节）；持 DRI 角色的 Agent 指派被拒见 '
                                            'an_agent_holding_the_dri_role_cannot_assign。'},
    **{kind: {'missing_declaration': _GATES_ARE_SIGNED_BY_PEOPLE} for kind in GATE_ACTIONS},
}

# 除矩阵检查外，写 world_api_accepted: true 还要求的环境门槛。
REQUIRED_GATES = {'source_unchanged', 'ordinary_application_privileges', 'immutable_history', 'no_external_effects'}

EXCLUDED = [
    'raw_evidence_storage（world 0.1 不上传证据）', 'existing_containers_preserved', 'deployment',
    'workbench_ui', 'real_model_and_codex_cli', 'concurrent_writes_and_restart_recovery', 'production_identity',
]
