"""Frozen required subchecks; group names alone cannot establish acceptance."""

REQUIRED = {
    "A1-01": ["install_exact_p1", "same_profile_idempotent", "different_content_conflict",
              "wrong_hash_rejected", "wrong_contract_ref_rejected", "p2_p3_do_not_rebind_n1",
              "no_public_arbitrary_registration"],
    "A1-02": ["real_old_source_and_schema", "old_http_history_created", "original_sql_columns_unchanged",
              "original_object_revision_receipt_reads", "original_context_and_evidence_unchanged",
              "no_ic_or_composition_success_backfilled"],
    "A1-03": ["missing_contract_denied", "explicit_null_contract_denied", "legacy_contract_denied",
              "unknown_contract_denied", "correct_contract_no_legacy_handler", "profile_injection_denied",
              "prepare_execute_same_fence", "hidden_object_does_not_leak_protocol"],
    "A1-04": ["trusted_legacy_create_atomic_binding", "new_domain_old_bc_ec_work_denied",
              "removed_parent_no_fallback", "old_parent_new_domain_denied",
              "cross_protocol_parent_denied", "scope_domain_policy_precedence_enforced"],
    "A1-05": ["generic_propose_fenced", "accept_activate_fenced", "adjustment_affected_set_fenced",
              "dedicated_delivery_fenced", "legacy_target_new_dependency_fenced",
              "unknown_fields_strict", "targetless_authority_control_explicit"],
    "A1-06": ["legacy_exact_dri_accepts", "legacy_v1_return_v2_accepts", "legacy_negative_authority",
              "delivery_outcome_mf_independent", "deliverable_created_with_binding",
              "legacy_current_revision_and_criteria"],
    "A1-07": ["missing_binding_denied", "unknown_binding_protocol_denied", "unsupported_profile_denied",
              "parent_binding_conflict_denied", "duplicate_binding_cannot_fork", "evidence_upload_atomic_binding",
              "evidence_new_unknown_disabled_denied_before_s3", "cross_scope_binding_fk_denied"],
    "A1-08": ["execute_revoked_new_write_denied", "read_retained_history_replay_allowed",
              "read_revoked_receipt_snapshot_replay_denied", "other_current_reader_retains_history",
              "all_receipt_and_snapshot_dependencies_reauthorized"],
    "A1-09": ["committed_response_loss_replays_same_receipt", "exactly_one_object_binding_event_receipt",
              "same_key_changed_body_conflict", "old_request_hash_35_golden_vectors",
              "old_http_requests_replay_after_migration", "replay_does_not_dispatch"],
    "A1-10": ["checkpoint_reached_before_commit", "injected_failure_rolls_back_object_binding_receipt",
              "same_key_retry_succeeds_once", "same_key_concurrent_create_no_fork",
              "concurrent_profile_or_binding_conflict_atomic"],
    "A1-11": ["real_app_nonowner_nonbypass", "all_new_tables_oracles_and_rls",
              "immutable_effective_table_column_rights", "cross_scope_fk_and_reads",
              "broad_insert_grant_cannot_register_profile_policy", "app_cannot_rebind",
              "security_definer_execute_catalog_and_denial_if_present"],
    "A1-12": ["objects_revisions_profile_metadata", "receipt_original_meaning_preserved",
              "context_pack_protocol_metadata", "workbench_direct_sql_metadata",
              "unsupported_interpretation_explicit", "ordinary_reads_no_business_write",
              "context_post_only_audit_snapshot", "narrative_protocol_recheck_if_enabled"],
    "A1-13": ["new_worker_unsupported_effect_no_http", "queue_metadata_cannot_select_legacy",
              "missing_or_mixed_binding_effect_denied", "legacy_effect_positive_control",
              "real_old_api_cannot_write", "real_old_worker_cannot_claim_or_dispatch",
              "preclaimed_old_task_cutover_precondition"],
    "A1-14": ["second_oneoff_database_old_history", "migration_replay_twice",
              "backfill_replay_twice", "new_write_disabled_history_readable",
              "disabled_no_legacy_fallback", "packaged_migration_profile_artifacts"],
}

assert len(REQUIRED) == 14
assert all(len(set(checks)) == len(checks) for checks in REQUIRED.values())
