"""Explicit compiled Method action/type registry, separate from legacy unions."""
from typing import Literal, Union
from .method_common_models import METHOD_COMMON_PARAMS, METHOD_COMMON_TARGETS, METHOD_COMMON_PAYLOADS
from .method_m1a_models import M1A_ACTION_PARAMS, M1A_ACTION_TARGETS, M1A_PAYLOAD_MODELS
from .method_m1b_models import M1B_ACTION_PARAMS, M1B_ACTION_TARGETS, M1B_PAYLOAD_MODELS

METHOD_ACTION_PARAMS = {**METHOD_COMMON_PARAMS, **M1A_ACTION_PARAMS, **M1B_ACTION_PARAMS}
METHOD_ACTION_TARGETS = {**METHOD_COMMON_TARGETS, **M1A_ACTION_TARGETS, **M1B_ACTION_TARGETS}
METHOD_PAYLOAD_MODELS = {**METHOD_COMMON_PAYLOADS, **M1A_PAYLOAD_MODELS, **M1B_PAYLOAD_MODELS}
METHOD_OBJECT_TYPES = frozenset(METHOD_PAYLOAD_MODELS) | {"EvidenceAsset"}
MethodActionType = Literal[tuple(METHOD_ACTION_PARAMS)]
MethodActionParams = Union[tuple(METHOD_ACTION_PARAMS.values())]
