#!/usr/bin/env bash
set -euo pipefail

release_id="${1:?release id required}"
image="${2:?preloaded Clark image required}"
app_root="/srv/tokenhub/apps/clark-main"
data_dir="/srv/tokenhub/data/clark-main"
env_file="/etc/tokenhub/clark-main.env"
nginx_template="/etc/tokenhub/nginx-clark-internal.conf"
nginx_config="/etc/nginx/sites-available/clark-internal.conf"
state_file="$app_root/current.env"
backup_root="/etc/tokenhub/runtime-cutover-backups"
release_dir="$app_root/releases/$release_id"

test "$(id -u)" = "0"
test -s "$env_file"
test -s "$nginx_template"
test -s "$state_file"
docker image inspect "$image" >/dev/null
test "$(docker image inspect "$image" --format '{{.Architecture}}/{{.Os}}')" = "amd64/linux"

# This file is generated by the existing deployment script and contains quoted IDs.
# shellcheck disable=SC1090
source "$state_file"
old_release="${CURRENT_RELEASE:?current release missing}"
old_container="${CURRENT_CONTAINER:?current container missing}"
old_port="${CURRENT_PORT:?current port missing}"
if test "$old_port" = "3121"; then new_port="3122"; else new_port="3121"; fi
new_container="clark-main-$release_id"
preflight_container="clark-preflight-$release_id"
preflight_data="/srv/tokenhub/data/clark-preflight-$release_id"

if docker container inspect "$new_container" >/dev/null 2>&1; then
  echo 'CLARK_TARGET_CONTAINER_ALREADY_EXISTS' >&2
  exit 1
fi
if ss -ltn | awk '{print $4}' | grep -Eq "(^|:)$new_port$"; then
  echo 'CLARK_TARGET_PORT_IN_USE' >&2
  exit 1
fi

install -d -m 700 "$backup_root"
install -d -m 755 "$release_dir"
install -d -m 755 "$preflight_data"
cp -a "$data_dir/." "$preflight_data/"
chown -R 1001:1001 "$preflight_data"

run_clark() {
  name="$1"; port="$2"; volume="$3"
  docker run -d \
    --name "$name" --restart unless-stopped --init \
    --cpus 4 --memory 4g --pids-limit 512 --cap-drop ALL \
    --security-opt no-new-privileges:true --stop-timeout 30 \
    --env-file "$env_file" -e "TKOS_CODE_SHA=$release_id" \
    -p "127.0.0.1:$port:3000" -v "$volume:/app/.data" "$image" >/dev/null
}

wait_health() {
  port="$1"
  for _ in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:$port/api/health" >/dev/null; then return 0; fi
    sleep 2
  done
  return 1
}

# First prove the image and new environment against an isolated copy of Clark data.
run_clark "$preflight_container" "$new_port" "$preflight_data"
if ! wait_health "$new_port"; then
  docker stop --time 30 "$preflight_container" >/dev/null 2>&1 || true
  echo 'CLARK_PREFLIGHT_FAILED' >&2
  exit 1
fi
docker stop --time 30 "$preflight_container" >/dev/null

# Final handover uses one writer for the authoritative Clark data directory.
docker stop --time 30 "$old_container" >/dev/null
data_backup="$backup_root/clark-data-$release_id-before.tgz"
tar -czf "$data_backup" -C "$data_dir" .
chmod 600 "$data_backup"
run_clark "$new_container" "$new_port" "$data_dir"
if ! wait_health "$new_port"; then
  docker stop --time 30 "$new_container" >/dev/null 2>&1 || true
  docker start "$old_container" >/dev/null
  echo 'CLARK_FINAL_HEALTH_FAILED_OLD_RESTARTED' >&2
  exit 1
fi

nginx_backup="$backup_root/clark-internal.conf.$release_id.before"
test ! -e "$nginx_backup"
cp -a "$nginx_config" "$nginx_backup"
chmod 600 "$nginx_backup"
sed "s/__UPSTREAM_PORT__/$new_port/g" "$nginx_template" > "$nginx_config.new"
chmod 644 "$nginx_config.new"
mv "$nginx_config.new" "$nginx_config"
if ! nginx -t >/dev/null 2>&1; then
  cp -a "$nginx_backup" "$nginx_config"
  chmod 644 "$nginx_config"
  docker stop --time 30 "$new_container" >/dev/null 2>&1 || true
  docker start "$old_container" >/dev/null
  echo 'CLARK_NGINX_TEST_FAILED_OLD_RESTORED' >&2
  exit 1
fi
systemctl reload nginx
if ! wait_health 3120; then
  cp -a "$nginx_backup" "$nginx_config"
  chmod 644 "$nginx_config"
  nginx -t >/dev/null 2>&1
  systemctl reload nginx
  docker stop --time 30 "$new_container" >/dev/null 2>&1 || true
  docker start "$old_container" >/dev/null
  wait_health "$old_port" || true
  echo 'CLARK_HANDOFF_HEALTH_FAILED_OLD_RESTORED' >&2
  exit 1
fi

cat > "$state_file" <<EOF
CURRENT_RELEASE='$release_id'
CURRENT_CONTAINER='$new_container'
CURRENT_PORT='$new_port'
PREVIOUS_RELEASE='$old_release'
PREVIOUS_CONTAINER='$old_container'
PREVIOUS_PORT='$old_port'
EOF
chmod 600 "$state_file"
cat > "$release_dir/deployment.json" <<EOF
{"release_id":"$release_id","image":"$image","port":$new_port,"previous_release":"$old_release","previous_container":"$old_container","previous_port":$old_port}
EOF
chmod 644 "$release_dir/deployment.json"
ln -sfn "$release_dir" "$app_root/current"

printf 'release=%s\ncontainer=%s\nport=%s\nprevious_container=%s\nhealth=ok\n' \
  "$release_id" "$new_container" "$new_port" "$old_container"
